name: Pull Request Trigger
on:
  pull_request:
    types: [opened, closed, reopened]
    branches: [gh-pages]
    
jobs:
  createCard:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'reopened'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          project-name: Project Board
          column-name: PR Needs review (Automated Column, do not place items here manually)
          issue-number: ${{ github.event.number }}


      - name: Check output
        run: echo ${{ steps.coupc.outputs.card-id }}

      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: 'Error! Cannot find a linked issue associated with this PR, Please link your issue by adding Fixes #<issue number goes here>'

     