name: Pull Request Trigger
on:
  pull_request:
    types: [opened, closed]
    branches: [gh-pages]
    
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened'}}
    steps:
     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Project Board
          column-name: PR Needs Review
          issue-number: ${{ github.event.number }}
      - name: Check output
        run: echo ${{ steps.coupc.outputs.card-id }}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        
        with:
          message: 'Sucessfully added PR to "PR Needs Review" column'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: tkt-actions/add-issue-links@v1.6.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}' # required
          branch-prefix: 'issue-' # required