name: Pull Request Trigger
on:
  pull_request:
    types: [opened, closed]
    branches:
      - 'gha-pull-request-trigger-2395'

jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
