name: Pull Request Trigger
on:
  pull_request:
    types: [opened, closed]
    branches: [gh-pages]
    

jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
       
      