name: Pull Request Trigger
on:
  pull_request:
    types: [opened, closed, reopened]
    branches: [gh-pages]
    
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'reopened'}}
    steps:
     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Project Board
          column-name: PR Needs Review
          issue-number: ${{ github.event.number }}
      - name: Check output
        run: echo ${{ steps }}
      
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        
        with:
          message: 'Sucessfully added PR to "PR Needs Review" column'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: 'Error! This is a custom error'

      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Linked Issues Action
        uses: kin/gh-action-get-linked-issues@v1.0
        id: linked-issues
        with:
          # Required: personal access token with permissions to archive cards. This needs to be set in Settings -> Secrets with a token that has permissions for all repos the issues are linked in for cross-repo functionality
          access-token: "${{ secrets.CROSS_REPO_TOKEN }}"

      